
export const eventIframes: string[] = [
    `<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fmunmsagroup%2Fposts%2Fpfbid0iwMfYR3WJyBLEPEkvYBUC2whgZFNFHL5tTpSDBV31kRXCTpZHATN9HiPKjFXEVSol&show_text=true&width=500" width="500" height="692" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>`,
    `<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fmunmsagroup%2Fposts%2Fpfbid02NYq34hsgVfduCWJpBLuo54uGtZkdNAiGfTiYtwEDKk6oVb7nckhqPUhLo2JQ2knPl&show_text=true&width=500" width="500" height="485" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>`,
    `<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fmunmsagroup%2Fposts%2Fpfbid0wDjZaRBQ4rEYt3pb5Roo7MsWBwcc9fW4Wi1iR77TD4ErHeUBBrzaB1pFd66ev2sjl&show_text=true&width=500" width="500" height="692" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>`,
    `<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fmunmsagroup%2Fposts%2Fpfbid0WE5YnyBu3n5fKvsmocupmM8eBa8uJ58KhhtrE1UgHY4PpsGwBft9z4DC8ty3HHY9l&show_text=true&width=500" width="500" height="648" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>`,
    `<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fmunmsagroup%2Fposts%2Fpfbid0fRMP2bZQH1jERKDVKAApapxF3SzKrViRb9zp91sJ5t7bWcg4ASTB9FaGV9DWmx9nl&show_text=true&width=500" width="500" height="479" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>`,
    `<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fmunmsagroup%2Fposts%2Fpfbid07TQFyLpS7hreFRewRmVgPuH7bH76ctagJ37h7nsQ9o4FDdWKip4UzqPFLQtHxGnhl&show_text=true&width=500" width="500" height="692" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>`,
    `<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fmunmsagroup%2Fposts%2Fpfbid02QikMSP5puL9fvN8Rih8EaA8SFvVcMxwCBThTqukqhZS5mQCu4MwEwyLmvR6RnQrdl&show_text=true&width=500" width="500" height="667" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>`,
    `<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fmunmsagroup%2Fposts%2Fpfbid0evC9pV3aQNnB7AoYS2cjbxBpJo8qjY6i6dPTQMi8Ltbeepdp4G3dS7r21fVsEWr5l&show_text=true&width=500" width="500" height="698" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>`,
]